"""
SynEval: Synthetic Data Evaluation Framework

A comprehensive evaluation framework for assessing the quality of synthetic data
generated by Large Language Models (LLMs).

The framework provides quantitative scoring across four key dimensions:
- Fidelity: Measures how well synthetic data preserves statistical properties
- Utility: Evaluates usefulness for downstream tasks
- Diversity: Assesses variety and uniqueness of generated data
- Privacy: Analyzes privacy protection level
"""

__version__ = "0.1.0"
__author__ = "Your Name"
__email__ = "your.email@example.com"
__description__ = "Synthetic Data Evaluation Framework"

# Import main classes for easy access
from .fidelity import FidelityEvaluator
from .utility import UtilityEvaluator
from .diversity import DiversityEvaluator
from .privacy import PrivacyEvaluator
from .plotting import PlottingEvaluator

# Import CLI function
from .cli import run_evaluation

__all__ = [
    "FidelityEvaluator",
    "UtilityEvaluator", 
    "DiversityEvaluator",
    "PrivacyEvaluator",
    "PlottingEvaluator",
    "run_evaluation",
    "__version__",
    "__author__",
    "__email__",
    "__description__"
] 