"""
Tests for CTGANLLMStitcher generator.

This generator demonstrates the Stitching Fallacy by generating tabular and text
data independently, then randomly pairing them.
"""
import pytest
import pandas as pd
import numpy as np
import tempfile
import os
from unittest.mock import Mock, patch, MagicMock
from generators.ctgan_llm_stitcher import CTGANLLMStitcher


@pytest.fixture
def sample_data():
    """Create sample dataset with text and tabular columns."""
    return pd.DataFrame({
        'review': [
            'This product is excellent! I love it.',
            'Terrible quality, waste of money.',
            'Pretty good, would recommend.',
            'Not bad but could be better.',
            'Amazing! Best purchase ever!'
        ],
        'rating': [5, 1, 4, 3, 5],
        'price': [29.99, 19.99, 24.99, 22.99, 34.99],
        'category': [1, 0, 1, 0, 1]
    })


@pytest.fixture
def mock_openai_client():
    """Create a mock OpenAI client."""
    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.choices = [MagicMock()]
    mock_response.choices[0].message.content = "This is a synthetic review generated by the model."
    mock_client.chat.completions.create.return_value = mock_response
    return mock_client


@pytest.fixture
def mock_anthropic_client():
    """Create a mock Anthropic client."""
    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_content = MagicMock()
    mock_content.text = "This is a synthetic review generated by Claude."
    mock_response.content = [mock_content]
    mock_client.messages.create.return_value = mock_response
    return mock_client


def test_ctgan_llm_stitcher_initialization():
    """Test that CTGANLLMStitcher can be initialized."""
    gen = CTGANLLMStitcher(provider='openai', model='gpt-4o-mini')
    assert gen.provider == 'openai'
    assert gen.model == 'gpt-4o-mini'
    assert gen.is_fitted is False


def test_ctgan_llm_stitcher_default_initialization():
    """Test default initialization."""
    gen = CTGANLLMStitcher()
    assert gen.provider == 'openai'
    assert gen.model == 'gpt-4o-mini'


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_fit(mock_ctgan, mock_openai_class, sample_data, mock_openai_client):
    """Test fitting the generator on sample data."""
    # Setup mocks
    mock_openai_class.return_value = mock_openai_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Set API key
    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai', model='gpt-4o-mini')
        gen.fit(
            sample_data,
            text_columns=['review'],
            tabular_columns=['rating', 'price', 'category']
        )

    # Verify state
    assert gen.is_fitted is True
    assert gen.text_columns == ['review']
    assert gen.tabular_columns == ['rating', 'price', 'category']
    assert len(gen.few_shot_examples['review']) > 0
    assert len(gen.few_shot_examples['review']) <= 5

    # Verify CTGAN was fitted on tabular columns only
    mock_ctgan_instance.fit.assert_called_once()
    fitted_df = mock_ctgan_instance.fit.call_args[0][0]
    assert set(fitted_df.columns) == {'rating', 'price', 'category'}


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_generate(mock_ctgan, mock_openai_class, sample_data, mock_openai_client):
    """Test generating synthetic samples."""
    # Setup mocks
    mock_openai_class.return_value = mock_openai_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Mock CTGAN generate
    mock_tabular_df = pd.DataFrame({
        'rating': [4, 3, 5],
        'price': [25.99, 21.99, 30.99],
        'category': [1, 0, 1]
    })
    mock_ctgan_instance.sample.return_value = mock_tabular_df

    # Fit and generate
    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai', model='gpt-4o-mini')
        gen.fit(
            sample_data,
            text_columns=['review'],
            tabular_columns=['rating', 'price', 'category']
        )

        synthetic_df = gen.generate(3)

    # Verify output
    assert len(synthetic_df) == 3
    assert set(synthetic_df.columns) == {'review', 'rating', 'price', 'category'}
    assert all(isinstance(text, str) for text in synthetic_df['review'])

    # Verify CTGAN sample was called
    mock_ctgan_instance.sample.assert_called_once_with(3)

    # Verify LLM was called for each text column sample
    assert mock_openai_client.chat.completions.create.call_count == 3


@patch('generators.ctgan_llm_stitcher.Anthropic')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_anthropic(mock_ctgan, mock_anthropic_class, sample_data, mock_anthropic_client):
    """Test using Anthropic provider."""
    # Setup mocks
    mock_anthropic_class.return_value = mock_anthropic_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Mock CTGAN generate
    mock_tabular_df = pd.DataFrame({
        'rating': [4, 3],
        'price': [25.99, 21.99],
        'category': [1, 0]
    })
    mock_ctgan_instance.sample.return_value = mock_tabular_df

    # Fit and generate
    with patch.dict(os.environ, {'ANTHROPIC_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='anthropic', model='claude-3-haiku-20240307')
        gen.fit(
            sample_data,
            text_columns=['review'],
            tabular_columns=['rating', 'price', 'category']
        )

        synthetic_df = gen.generate(2)

    # Verify output
    assert len(synthetic_df) == 2
    assert 'review' in synthetic_df.columns

    # Verify Anthropic API was called
    assert mock_anthropic_client.messages.create.call_count == 2


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_independence(mock_ctgan, mock_openai_class, sample_data, mock_openai_client):
    """
    Test that text and tabular data are independent (demonstrating Stitching Fallacy).

    This is the key test: we verify that the pairing is random by checking that
    text samples are shuffled relative to tabular samples.
    """
    # Setup mocks
    mock_openai_class.return_value = mock_openai_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Mock CTGAN to return ordered data
    mock_tabular_df = pd.DataFrame({
        'rating': list(range(10)),
        'price': [float(i * 10) for i in range(10)],
        'category': [i % 2 for i in range(10)]
    })
    mock_ctgan_instance.sample.return_value = mock_tabular_df

    # Mock LLM to return numbered text (so we can track order)
    def mock_llm_response(*args, **kwargs):
        response = MagicMock()
        response.choices = [MagicMock()]
        # Use call count to generate numbered text
        call_num = mock_openai_client.chat.completions.create.call_count
        response.choices[0].message.content = f"Review number {call_num}"
        return response

    mock_openai_client.chat.completions.create.side_effect = mock_llm_response

    # Fit and generate with fixed seed for reproducibility
    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai', model='gpt-4o-mini', random_seed=42)
        gen.fit(
            sample_data,
            text_columns=['review'],
            tabular_columns=['rating', 'price', 'category']
        )

        synthetic_df = gen.generate(10)

    # Extract review numbers from text
    review_numbers = [int(text.split()[-1]) for text in synthetic_df['review']]

    # If not shuffled, review_numbers would be [1,2,3,...,10]
    # After shuffling, they should be in different order
    # We verify they are NOT in sequential order
    assert review_numbers != list(range(1, 11))

    # But all numbers should still be present (just reordered)
    assert set(review_numbers) == set(range(1, 11))


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_save_load(mock_ctgan, mock_openai_class, sample_data, mock_openai_client):
    """Test save and load functionality."""
    # Setup mocks
    mock_openai_class.return_value = mock_openai_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Fit generator
    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai', model='gpt-4o-mini')
        gen.fit(
            sample_data,
            text_columns=['review'],
            tabular_columns=['rating', 'price', 'category']
        )

        # Save to temporary file
        with tempfile.NamedTemporaryFile(mode='wb', delete=False, suffix='.pkl') as f:
            temp_path = f.name

        try:
            gen.save(temp_path)
            assert os.path.exists(temp_path)

            # Load into new generator
            loaded_gen = CTGANLLMStitcher()
            loaded_gen.load(temp_path)

            # Verify state was preserved
            assert loaded_gen.is_fitted == gen.is_fitted
            assert loaded_gen.text_columns == gen.text_columns
            assert loaded_gen.tabular_columns == gen.tabular_columns
            assert loaded_gen.provider == gen.provider
            assert loaded_gen.model == gen.model
            assert loaded_gen.few_shot_examples == gen.few_shot_examples

        finally:
            if os.path.exists(temp_path):
                os.remove(temp_path)


def test_ctgan_llm_stitcher_missing_api_key():
    """Test that missing API key raises clear error."""
    with patch.dict(os.environ, {}, clear=True):
        gen = CTGANLLMStitcher(provider='openai')

        with pytest.raises(ValueError) as exc_info:
            gen.fit(
                pd.DataFrame({'text': ['test'], 'num': [1]}),
                text_columns=['text'],
                tabular_columns=['num']
            )

        assert "OPENAI_API_KEY" in str(exc_info.value)


def test_ctgan_llm_stitcher_invalid_provider():
    """Test that invalid provider raises error."""
    with pytest.raises(ValueError) as exc_info:
        CTGANLLMStitcher(provider='invalid_provider')

    assert "provider must be" in str(exc_info.value).lower()


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_generate_before_fit(mock_ctgan, mock_openai_class, mock_openai_client):
    """Test that generate raises error if called before fit."""
    mock_openai_class.return_value = mock_openai_client

    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai')

        with pytest.raises(ValueError) as exc_info:
            gen.generate(5)

        assert "must be fitted" in str(exc_info.value).lower()


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_multiple_text_columns(mock_ctgan, mock_openai_class, mock_openai_client):
    """Test handling multiple text columns."""
    # Setup mocks
    mock_openai_class.return_value = mock_openai_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Create data with multiple text columns
    multi_text_data = pd.DataFrame({
        'review': ['Great!', 'Bad.', 'Okay.'],
        'summary': ['Excellent product', 'Poor quality', 'Average item'],
        'rating': [5, 1, 3]
    })

    # Mock CTGAN generate
    mock_tabular_df = pd.DataFrame({'rating': [4, 3]})
    mock_ctgan_instance.sample.return_value = mock_tabular_df

    # Fit and generate
    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai', model='gpt-4o-mini')
        gen.fit(
            multi_text_data,
            text_columns=['review', 'summary'],
            tabular_columns=['rating']
        )

        synthetic_df = gen.generate(2)

    # Verify output has both text columns
    assert 'review' in synthetic_df.columns
    assert 'summary' in synthetic_df.columns
    assert 'rating' in synthetic_df.columns

    # Verify LLM was called for both text columns (2 samples * 2 text columns = 4 calls)
    assert mock_openai_client.chat.completions.create.call_count == 4


@patch('generators.ctgan_llm_stitcher.OpenAI')
@patch('generators.ctgan_llm_stitcher.GaussianCopulaSynthesizer')
def test_ctgan_llm_stitcher_few_shot_extraction(mock_ctgan, mock_openai_class, sample_data, mock_openai_client):
    """Test that few-shot examples are correctly extracted."""
    # Setup mocks
    mock_openai_class.return_value = mock_openai_client
    mock_ctgan_instance = MagicMock()
    mock_ctgan.return_value = mock_ctgan_instance

    # Fit generator
    with patch.dict(os.environ, {'OPENAI_API_KEY': 'test-key'}):
        gen = CTGANLLMStitcher(provider='openai', n_few_shot=3)
        gen.fit(
            sample_data,
            text_columns=['review'],
            tabular_columns=['rating', 'price', 'category']
        )

    # Verify few-shot examples
    assert 'review' in gen.few_shot_examples
    assert len(gen.few_shot_examples['review']) == 3

    # All examples should be from original data
    for example in gen.few_shot_examples['review']:
        assert example in sample_data['review'].values
